server:
  servlet:
    context-path: /base
spring:
  datasource:
    url: "jdbc:h2:mem:"
    username: sa
    password:
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    web: debug
